squid_full:
  image: sameersbn/squid:3.5.27-2
  ports:
    - "3128:3128"
  volumes:
#       - ./logs:/var/log/squid
#       - ./data:/var/spool/squid
    - ./squid.conf:/etc/squid/squid.conf
    - ./htpasswd:/etc/squid/squid_passwd
#     - /srv/docker/squid/cache:/var/spool/squid
  restart: always
  environment:
#       TZ: UTC
    CFLAGS: " -Dbind=SOCKSbind "
    CXXFLAGS: " -Dbind=SOCKSbind "
    LDADD: " -lsocks "
