Squid:
  image: sameersbn/squid:3.5.27-2
  ports:
    - "3128:3128"
  volumes:
    - ./squid.conf:/etc/squid/squid.conf
    - ./htpasswd:/etc/squid/squid_passwd
    - /srv/docker/squid/cache:/var/spool/squid
  restart: always
  environment:
    CFLAGS: " -Dbind=SOCKSbind "
    CXXFLAGS: " -Dbind=SOCKSbind "
    LDADD: " -lsocks "
