squid_full:
  image: ubuntu/squid
  ports:
    - "3128:3128"
#   volumes:
#     - ./squid.conf:/etc/squid/squid.conf
#     - ./htpasswd:/etc/squid/squid_passwd
#     - /srv/docker/squid/cache:/var/spool/squid
  restart: always
  environment:
      TZ: UTC
#     CFLAGS: " -Dbind=SOCKSbind "
#     CXXFLAGS: " -Dbind=SOCKSbind "
#     LDADD: " -lsocks "
